services:
  - type: web
    name: cd-shopify-proxy-starter
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 3000
      - key: CD_API_BEARER
        sync: false
